---
output: github_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(message = FALSE)
```

# [1148. Article Views I](https://leetcode.com/problems/article-views-i/)

  * [Python Solution](#python)
  * [R Solution](#r)
  
# Problem

```
Table: Views

+---------------+---------+
| Column Name   | Type    |
+---------------+---------+
| article_id    | int     |
| author_id     | int     |
| viewer_id     | int     |
| view_date     | date    |
+---------------+---------+
There is no primary key (column with unique values) for this table, the table may have duplicate rows.

Each row of this table indicates that some viewer viewed an article (written by some author) on some date. 

Note that equal author_id and viewer_id indicate the same person.
``` 

Write a solution to find all the authors that viewed at least one of their own articles.

Return the result table sorted by `id` in ascending order.

## Data

```{python}
import pandas as pd

data = [[1, 3, 5, '2019-08-01'], [1, 3, 6, '2019-08-02'], [2, 7, 7, '2019-08-01'], [2, 7, 6, '2019-08-02'], [4, 7, 1, '2019-07-22'], [3, 4, 4, '2019-07-21'], [3, 4, 4, '2019-07-21']]
views = pd.DataFrame(data, columns=['article_id', 'author_id', 'viewer_id', 'view_date']).astype({'article_id':'int', 'author_id':'int', 'viewer_id':'int', 'view_date':'datetime64[ns]'})

r.views = views
```

## Python

```{python}
def article_views(views: pd.DataFrame) -> pd.DataFrame:
    
    df = views[views['author_id'] == views['viewer_id']]
    df = df.rename(columns={'author_id': 'id'})

    df = df.sort_values(by = ['id'])
    df = df.drop_duplicates(['id'])

    return df[['id']]
  
print(article_views(views))
```

## R

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)

article_views <- function(views){
  
  res <- views %>%
    filter(author_id == viewer_id) %>%
    rename(id = author_id) %>%
    arrange(id) %>%
    distinct(id) %>%
    select(id)
  
  return(res)
}

print(article_views(views))
```
